//! PuTTY key files, against files PuTTY itself wrote.
//!
//! A comment in `sftp/auth.rs` once said `.ppk` needed its own parser and would
//! arrive with a later milestone. That turned out to be wrong twice over:
//! `russh` recognises the header and reads the file, and the pieces both
//! versions need — AES for v2 and v3, Argon2 for v3 — are already in the tree
//! through russh itself. So the work was to find out, not to build.
//!
//! Finding out means real files. These are generated by `puttygen` when it is
//! on the machine, and the test skips itself when it is not — a private key,
//! even a throwaway one, does not go in the repository.

use std::path::{Path, PathBuf};
use std::process::Command;

fn puttygen() -> Option<PathBuf> {
    for candidate in [
        "/opt/homebrew/bin/puttygen",
        "/usr/local/bin/puttygen",
        "/usr/bin/puttygen",
    ] {
        let path = PathBuf::from(candidate);
        if path.is_file() {
            return Some(path);
        }
    }
    None
}

/// Makes one key, and answers where it landed.
fn make(
    tool: &Path,
    dir: &Path,
    name: &str,
    kind: &str,
    version: &str,
    passphrase: &str,
) -> PathBuf {
    let secret = dir.join("passphrase");
    std::fs::write(&secret, passphrase).expect("write the passphrase file");

    let target = dir.join(name);
    let mut command = Command::new(tool);
    command
        .args(["-t", kind, "-O", "private", "-o"])
        .arg(&target)
        .args(["--new-passphrase"])
        .arg(&secret)
        .args(["-C", "amberbeam test key"]);
    if version == "2" {
        command.args(["--ppk-param", "version=2"]);
    }
    if kind == "rsa" {
        command.args(["-b", "2048"]);
    }

    let done = command.output().expect("run puttygen");
    assert!(
        target.is_file(),
        "puttygen wrote nothing: {}",
        String::from_utf8_lossy(&done.stderr)
    );
    target
}

#[test]
fn putty_keys_of_both_versions_are_read() {
    let Some(tool) = puttygen() else {
        eprintln!("skipping: puttygen is not on this machine");
        return;
    };

    let dir = std::env::temp_dir().join(format!("amberbeam-ppk-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&dir);
    std::fs::create_dir_all(&dir).expect("scratch directory");

    // Version 3 is the current one and derives its key with Argon2; version 2
    // is what every file written before PuTTY 0.75 looks like, and those are
    // exactly the files somebody moving from Windows still has.
    let cases: [(&str, &str, &str, &str); 4] = [
        ("v3-open.ppk", "ed25519", "3", ""),
        ("v3-sealed.ppk", "ed25519", "3", "tannenbaum"),
        ("v2-open.ppk", "rsa", "2", ""),
        ("v2-sealed.ppk", "rsa", "2", "tannenbaum"),
    ];

    for (name, kind, version, passphrase) in cases {
        let path = make(&tool, &dir, name, kind, version, passphrase);
        let header = std::fs::read_to_string(&path)
            .expect("read it back")
            .lines()
            .next()
            .unwrap_or_default()
            .to_string();
        assert!(
            header.starts_with(&format!("PuTTY-User-Key-File-{version}")),
            "asked for version {version}, got {header}"
        );

        let key =
            russh::keys::load_secret_key(&path, (!passphrase.is_empty()).then_some(passphrase))
                .unwrap_or_else(|error| panic!("{name} could not be read: {error}"));
        eprintln!("{name}: {}", key.algorithm());
    }

    // And the one failure that has to be a failure: the wrong passphrase must
    // not quietly produce a key that then fails to log in.
    let sealed = dir.join("v3-sealed.ppk");
    assert!(
        russh::keys::load_secret_key(&sealed, Some("falsch")).is_err(),
        "a wrong passphrase must be refused, not worked around"
    );
    assert!(
        russh::keys::load_secret_key(&sealed, None).is_err(),
        "an encrypted key without a passphrase must be refused"
    );

    let _ = std::fs::remove_dir_all(&dir);
}
